<?php

$sql =  " SELECT A.NAME,A.SALARY_NOW,A.SALARY_NEW, A.SALARY_SPE_NOW,A.SALARY_SPE_NEW,A.SAL_COMPENSATION_4,A.SALARY_UP,A.SCORE_PERCENT, A.LEVEL_SALARY_MID ,J.LEVEL_NAME,A.REMARKS,B.PER_IDCARD, A.PER_ID,  
 A.POS_NO, A.SALARY_SPE_UP,A.SAL_UP_ID, TYPE_NAME_TH,LEVEL_NAME_TH,
LINE_NAME_TH,F.ORG_NAME_TH AS ORG_NAME_3 , H.ORG_NAME_TH AS ORG_NAME_4, G.MANAGE_NAME_TH, 
A.ORG_ID_4, A.SCORE
FROM SAL_UP_SALARY A 
INNER JOIN PER_PROFILE B ON A.PER_ID = B.PER_ID 
LEFT JOIN SETUP_POS_TYPE C ON A.TYPE_ID = C.TYPE_ID 
LEFT JOIN SETUP_POS_LINE D ON A.LINE_ID = D.LINE_ID 
LEFT JOIN SETUP_POS_LEVEL E ON A.LEVEL_ID = E.LEVEL_ID 
LEFT JOIN SETUP_ORG F ON A.ORG_ID_3 = F.ORG_ID 
LEFT JOIN SETUP_ORG H ON A.ORG_ID_4 = H.ORG_ID 
LEFT JOIN SETUP_POS_MANAGE G ON A.MANAGE_ID = G.MANAGE_ID 
LEFT JOIN SAL_SCORE I ON A.SCORE_ID = I.SCORE_ID 
LEFT JOIN SAL_LEVEL_SCORE J ON I.LV_SCORE_ID = J.LV_SCORE_ID 
			  ";
    $sql .= " WHERE A.YEAR_BDG = '".$AGE_IS."' AND A.CONFIRM_TYPE = 2 AND A.ROUND = '".$ROUND."' AND  A.SALARY_SPE_UP > 0 AND A.POSTYPE_ID = 1  ";
$sql .= "  ORDER BY F.ORG_NAME_TH ASC ";  
$query = $db->query($sql);
$nums = $db->db_num_rows($query);  


	 

							
?>